# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MangoPractice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKit'
pod 'YouTubePlayer-Swift', '~> 1.0'
pod 'Alamofire', '~> 4.7'
  # Pods for MangoPractice

end
