# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'MangoPractice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKit', '~> 4.0.0'
pod 'YouTubePlayer-Swift', '~> 1.0'
pod 'Alamofire', '~> 4.7'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'FBSDKCoreKit', '~> 4.38.1'
pod 'FBSDKShareKit', '~> 4.38.1'
pod 'FBSDKLoginKit', '~> 4.38.1'
pod 'Kingfisher'



  # Pods for MangoPractice

end
